### ISSUE TITLE
[Bug]: App Crash when selecting a specific lecture in the Timetable

### ISSUE THREAD

**Issue by pl0ss** [neuland-ingolstadt/neuland.app-native#129]
### Before submitting a new issue

- [X] I checked for app updates and the bug is present in the latest version.
- [X] I checked the [status page](https://status.neuland.app) and the issue is not listed there.
- [X] I checked for possible duplicate issues, but couldn't find any.

### Bug summary

Wenn ich im Stundenplan die Vorlesung AWT anklicke, dann erhalte ich die Fehlermeldung:
Internal Error; Neuland Next has encountered an internal error.
Wenn ich Feedback versenden möchte, dann steht im Email Body: Fehler: Cannot read property 'split' of null

AWT (CAI_AWT Advanced Webtechnologies) findet man unter der Studiengruppe: INF-FW

### App platform

iOS

### Device

iPhone 13

### OS version

18.1.1

### App version

0.10.1

### Steps to reproduce

1. AWT im Stundenplan anklicken

### Expected behavior

:)

**Comment by Robert27** [comment]
Fix will be part of upcoming 0.11.0
