### ISSUE TITLE
Changing flags and allergens slow and buggy

### ISSUE THREAD

**Issue by BuildmodeOne** [neuland-ingolstadt/neuland.app-native#43]
Clicking the allergenes or flags repeatlatly  will lead to some weird behaviour as shown in the two videos.
Additionally, the app is not responsive (e.g. going back) until all these actions are finished.

- Android 14, OneUI 6.0
- [0d37bda](https://github.com/neuland-ingolstadt/neuland.app-native/pull/42/commits/0d37bdab6da7165ff3ef9e2412306d8343571d68)

Recordings:
https://github.com/neuland-ingolstadt/neuland.app-native/assets/39560569/b95da4b3-034e-4ef4-8ba2-221e48b83d25
https://github.com/neuland-ingolstadt/neuland.app-native/assets/39560569/0f3c747b-f71f-490d-9660-a3e23134ea30

**Comment by Robert27** [comment]
The problem was the UseContext FoodFilter Hook, which became far too large and thus took a long time to load.
Fixed in #45, but could certainly be further improved.
