### ISSUE TITLE
Add a feature graphic for the native app stores

### ISSUE THREAD

**Issue by CrsiX** [neuland-ingolstadt/neuland.app-native#72]
In order to further setup a good "page" on the native application stores, we should have a feature graphic, which is usually shown above the name of the application and its details. Think of it as the promotion banner of the application.

This image must be in PNG or JPG format, landscape orientation, named `featureGraphic.png`/`featureGraphic.jpg` and placed in `fastlane/metadata/android/en-US/images` (for F-Droid, but I think this is also true for Google Play Store, at least).

**Comment by Robert27** [comment]
Some examples:
![1](https://github.com/user-attachments/assets/e95326f7-eac7-4ac2-b86f-3e30c091c65a)
![3](https://github.com/user-attachments/assets/01135b3c-db62-4dfa-9f1a-5e0df00e3681)
![5](https://github.com/user-attachments/assets/3840cc34-76c4-4f51-b888-ee0c9b4a5df2)
