### ISSUE TITLE
Food thumbnail 

### ISSUE THREAD

**Issue by Fledermaunz** [neuland-ingolstadt/neuland.app-native#73]
Maybe you could add little photos of the food served in Mensa 'cause it's often the same.
You could also use the beta users to collect photos of the food.

**Comment by BuildmodeOne** [comment]
There are multiple problems with food thumbnails why we can't and won't implement this:
- at first, we need pictures for every meal, but we can't rely on multiple beta testers here with different image styles and quality
- visual consistency (different image styles and quality)
- content moderation for image upload
- changing meal names (and pseudo-unique IDs from our API)

thanks for the suggestion :)
