### ISSUE TITLE
NFC Reading function for the Students ID

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/neuland.app-native#76]
Since it's a bit of a pain in the ass to always remember how much money is on the Students ID we could integrate a NFC Reading function so we can e.g. get the current balance, save it in the cookies and display it somewhere?

Or are we with this violating the TOS of THI because we are reading the ID with unauthorized machines?

**Comment by Robert27** [comment]
Legally not possible at this moment. 
Let’s hope for some API changes rather than breaking the encryption.
